### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Atemu** [stefansundin/bluesnooze#10]
Hi, the MIT license as added to the upstream repo, so you should probably copy that over.

Without a license you don't have permission to do these changes. Now, in actuality the code is license under MIT but it only allows you to redistribute and/or modify if the copyright notice is retained which it is currently not. Copying the LICENSE over would fulfill that requirement.

**Comment by stefansundin** [comment]
Fixed with 06aca06bd24482bc7ed75433f6cf2ecd878fa684.
