### ISSUE TITLE
Nothing happens after running the app in Sonoma 14.4.1

### ISSUE THREAD

**Issue by mikaelxu** [stefansundin/bluesnooze#11]
Hi, 

Did the installation per your instructions (system settings, open anyway, etc.).
Then ran the app. I can see the icon flashes once, then nothing happens. No icon on the menu bar.

**Comment by stefansundin** [comment]
Hello,

It seems to work ok for me on macOS 14.5. If there are no error messages then I'm not sure how to check what went wrong. Could you perhaps try opening it using the Terminal? I'm just hoping that that might print an error message.

Open the Terminal app and then run:

```
/Applications/Bluesnooze.app/Contents/MacOS/Bluesnooze
```

For me it asks for Bluetooth permissions, which I guess is granted automatically when run normally.

Did the original Bluesnooze work at all for you? https://github.com/odlp/bluesnooze

Maybe try older versions and see if any of them work?

**Comment by mikaelxu** [comment]
Sorry I forgot to mention that mine is a Hackintosh... using a BCM943224 WiFi+BT card.
This might be outside the app's intended support hardware.
I apologize for that. Let me close the issue for now.
