### ISSUE TITLE
[Feature Request] Add subtext as helper text in drop down menu

### ISSUE THREAD

**Issue by nisrulz** [stefansundin/bluesnooze#3]
Adding a grayed out text right under the "Hide Icon" option, would be a nice place to add the extra info needed to unhide the icon.

This is how I was thinking it would look like.

Text:
> Relaunch app to unhide icon

Screenshot:
![Group-9](https://user-images.githubusercontent.com/2096087/190990632-ed923a6a-5758-4600-aa61-8be1a67dca5c.png)

Side note: Thank you for your efforts to update this app. Very much appreciated 👏🏼

**Comment by stefansundin** [comment]
It doesn't seem like this subtext UI is a standard thing? At least I can't find anything like it in the NSMenuItem docs. https://developer.apple.com/documentation/appkit/nsmenuitem

I'm not that familiar with macOS development so I don't know the best way to implement this.

I was able to add a tooltip and that looks like this: https://github.com/stefansundin/bluesnooze/commit/bff4a73a617c249cadd6ad98cb6891206effd9ee

<img width="437" alt="Screen Shot 2022-10-01 at 14 06 32" src="https://user-images.githubusercontent.com/1991151/193428417-8cd55602-2cc4-45d0-8e00-a026166441c0.png">

So maybe that's good enough?

**Comment by stefansundin** [comment]
I added this message box that appears when you hide the icon. If you click <kbd>Cancel</kbd> then you cancel hiding the icon. If you click <kbd>OK</kbd> then the icon is hidden. It appears every time you hide the icon.

https://github.com/stefansundin/bluesnooze/commit/e7e0f1601cbbbfeff97db819b61d662a29d8b7e3

<img width="372" alt="Screen Shot 2022-10-01 at 15 10 52" src="https://user-images.githubusercontent.com/1991151/193430241-b36a2af1-9c9d-4862-91fd-8ff09c1c5c38.png">

I think that should solve this issue. Please let me know if there's even more we can do with this. I'm not going to release another version just for this but it'll be in the code for whenever the next version is released.

**Comment by stefansundin** [comment]
New version with this included has now been released. Also some other nice stuff like Wi-Fi support.

**Comment by nisrulz** [comment]
Just installed the new version and it works as expected. Thank you for adding the updates and making the release :)
